services:

  postgres:
    image: postgres:16
    container_name: hoian-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: hoian_db
      POSTGRES_USER: hoian
      POSTGRES_PASSWORD: hoian123

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./version_1.0.sql:/docker-entrypoint-initdb.d/01-version_1.0.sql:ro

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U hoian -d hoian_db"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  redis:
    image: redis:7-alpine
    container_name: hoian-redis

    restart: unless-stopped

    ports:
      - "6380:6379"

    volumes:
      - redis_data:/data

    command: redis-server --appendonly yes

    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "ping"
        ]
      interval: 5s
      timeout: 3s
      retries: 10


  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: hoian-app

    restart: unless-stopped

    ports:
      - "8888:8080"

    environment:

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hoian_db
      SPRING_DATASOURCE_USERNAME: hoian
      SPRING_DATASOURCE_PASSWORD: hoian123

      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

      SPRING_JPA_HIBERNATE_DDL_AUTO: validate

    depends_on:

      postgres:
        condition: service_healthy

      redis:
        condition: service_healthy


volumes:
  postgres_data:
  redis_data: